export interface Contact {
  id:           number;
  org:          boolean;
  name:         string;
  title:        string;
  biz:          string;
  slogan:       string;
  mobile:       string;
  bizPhone:     string;
  email:        string;
  bizEmail:     string;
  siteName:     string;
  website:      string;
  addr:         string;
  bizAddr:      string;
  calLink:      string;
  gglLink:      string;
  gglRev:       string;
  gglMap:       string;
  fbLink:       string;
  instaLink:    string;
  linkedIn:     string;
  twitterLink:  string;
  gitHub:       string;
  stkOvrflow:   string;
  mainColor:    string;
  secColor:     string;
  accColor:     string;
}
