import { Contact } from "./contact";

export const CONTACT: Contact[] = [
  {
    id :              0,
    name:             'Ryan & Tiffany',
    title:            'Success Consultant',
    biz:              'AmWay',
    slogan:           'You Are Who You Associate With',
    mobile:           '(720) 260-0407',
    bizPhone:         '(303) 961-6533',
    email:            'rynelson02@gmail.com',
    bizEmail:         'tiffmperez@yahoo.com',
    siteName:         'Checkout The Shop!',
    website:          'amway.com/myshop/ryntiffsmall',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/rynelson02',
    gglLink:          '',
    gglRev:           '',
    gglMap:           '',
    instaLink:        'https://instagram.com/rynel02?r=nametag',
    linkedIn:         '',
    twitterLink:      '',
    fbLink:           'https://m.facebook.com/ryan.nelson.79274',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        '#81D8D0',
    secColor:         '#e5e4e2',
    accColor:         '#e5e4e2'
  },
  // {
  //   id :              1,
  //   name:             'Ryan & Tiffany',
  //   title:            'Success Coach',
  //   biz:              'AmWay',
  //   slogan:           'You Are Who You Associate With',
  //   mobile:           '(720) 260-0407',
  //   bizPhone:         '(303) 961-6533',
  //   email:            'rynelson02@gmail.com',
  //   bizEmail:         'tiffmperez@yahoo.com',
  //   siteName:         'Checkout The Shop!',
  //   website:          'amway.com/myshop/ryntiffsmall',
  //   addr:             '',
  //   bizAddr:          '',
  //   calLink:          'https://calendly.com/rynelson02',
  //   gglLink:          '',
  //   gglRev:           '',
  //   gglMap:           '',
  //   instaLink:        'https://instagram.com/rynel02?r=nametag',
  //   linkedIn:         '',
  //   twitterLink:      '',
  //   fbLink:           'https://m.facebook.com/ryan.nelson.79274',
  //   gitHub:           '',
  //   stkOvrflow:       '',
  //   mainColor:        '#81D8D0',
  //   secColor:         '#414141',
  //   accColor:         '#e5e4e2'
  // },
  {
    id :              2,
    name:             'Lisa Keck',
    title:            'Owner',
    biz:              'Plain & Fancy Caterers',
    slogan:           'For The Love of Food',
    mobile:           '(336) 688-7787',
    bizPhone:         '(336) 869-4842',
    email:            'jtkeck1@msn.com',
    bizEmail:         '',
    siteName:         '',
    website:          'plainandfancycaterers.com',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/pfcateter/15min',
    gglLink:          'https://goo.gl/maps/FsQTpJWXtLYwu37Q8',
    gglRev:           '',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    fbLink:           'https://facebook.com/triadspecialevents',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        'white',
    secColor:         'red',
    accColor:         'black'
  },
  {
    id :              3,
    name:             'Carla Pomicter',
    title:            'IT Compliance Analyst',
    biz:              'DHI Mortgage Company, Ltd.',
    slogan:           'Founded In Family, Built On Commitment',
    mobile:           '(412) 952-4404',
    bizPhone:         '(512) 257-5498',
    email:            '',
    bizEmail:         'cpomicter@dhimortgage.com',
    siteName:         '',
    website:          'dhimortgage.com',
    addr:             '',
    bizAddr:          '',
    calLink:          '',
    gglLink:          '',
    gglRev:           '',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    fbLink:           '',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },
  {
    id :              4,
    name:             'James Keck',
    title:            'Software Developer | CEO | Creator of Ideas',
    biz:              'M|M Developers',
    slogan:           '2-Day Hand-coded Websites',
    mobile:           '(336) 880-0967',
    bizPhone:         '',
    email:            'jakkeck@gmail.com',
    bizEmail:         'james@magicmirror.dev',
    siteName:         '',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'https://g.page/mmdevs/review?rc',
    gglMap:           '',
    instaLink:        'https://facebook.com/mmdevs',
    linkedIn:         'https://linkedin.com/in/keck-james-keck',
    twitterLink:      'https://twitter.com/_techtranslator',
    fbLink:           'https://facebook.com/mmdevs',
    gitHub:           'https://github.com/MagicMirrorTech',
    stkOvrflow:       'https://facebook.com/mmdevs',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              5,
    name:             'Cameron Montes',
    title:            'Operations Specialist',
    biz:              'Best Deal In Town',
    slogan:           '#1 Rated Electronics Store in Denver',
    mobile:           '(720) 272-1279',
    bizPhone:         '(303) 593-0581',
    email:            '',
    bizEmail:         'cameronbestdealdenver@gmail.com',
    siteName:         '',
    website:          'bestdealdenver.com',
    addr:             '4371 S Broadway Englewood, CO 80113',
    bizAddr:          '',
    calLink:          'https://calendly.com/bdit/install',
    gglLink:          'https://g.page/bestDealDenver?gm',
    gglRev:           'http://g.page/bestDealDenver/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    fbLink:           'https://facebook.com/DenverHDTV',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              6,
    name:             'James Keck',
    title:            'Owner',
    biz:              'Best Deal In Town',
    slogan:           '#1 Rated Electronics Store in Denver',
    mobile:           '(336) 880-0967',
    bizPhone:         '(303) 593-0581',
    email:            'jakkeck@gmail.com',
    bizEmail:         'best.deal.in.denver@gmail.com',
    siteName:         '',
    website:          'bestdealdenver.com',
    addr:             '',
    bizAddr:          '4371 S Broadway Englewood, CO 80113',
    calLink:          'https://calendly.com/james-keck/connect',
    gglLink:          'https://g.page/bestDealDenver?gm',
    gglRev:           'http://g.page/bestDealDenver/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'https://linkedin.com/in/keck-james-keck',
    twitterLink:      'https://twitter.com/_techtranslator',
    fbLink:           'https://facebook.com/DenverHDTV',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },
  {
    id :              7,
    name:             'Jerius Guzman',
    title:            'Marketing Specialist',
    biz:              'Best Deal In Town',
    slogan:           '#1 Rated Electronics Store in Denver',
    mobile:           '(720) 656-1563',
    bizPhone:         '(303) 593-0581',
    email:            'jerius2007@gmail.com',
    bizEmail:         'best.deal.in.denver@gmail.com',
    siteName:         '',
    website:          'bestdealdenver.com',
    addr:             '',
    bizAddr:          '4371 S Broadway Englewood, CO 80113',
    calLink:          'https://calendly.com/bdit/install',
    gglLink:          'https://g.page/bestDealDenver?gm',
    gglRev:           'http://g.page/bestDealDenver/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    fbLink:           'https://facebook.com/DenverHDTV',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              8,
    name:             'Andie Fernandez',
    title:            'Community Manager',
    biz:              'M|M Developers',
    slogan:           '2-Day Hand-coded Websites',
    mobile:           '+52 (55) 3434-3745',
    bizPhone:         '',
    email:            'cocosnar@gmail.com',
    bizEmail:         'andie@magicmirror.dev',
    siteName:         '',
    website:          'https://magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'https://g.page/mmdevs/review?rc',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'https://linkedin.com/in/keck-james-keck',
    twitterLink:      'https://twitter.com/_techtranslator',
    fbLink:           'https://facebook.com/mmdevs',
    gitHub:           'https://github.com/MagicMirrorTech',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              9,
    name:             'Jorge Martinez',
    title:            'Full-Stack Developer',
    biz:              'M|M Developers',
    slogan:           'If you want you can fly, you just have to trust',
    mobile:           '+52 (77) 1132-7447',
    bizPhone:         '',
    email:            'jemc0810@gmail.com',
    bizEmail:         'jorge@magicmirror.dev',
    siteName:         '',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/jorgemtzcrz',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'http://g.page/mmdevs/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'https://linkedin.com/in/jorgemtzcrz',
    twitterLink:      '',
    fbLink:           'https://facebook.com/mmdevs',
    gitHub:           'https://github.com/JorgeMtzCrz',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },


  {
    id :              10,
    name:             'Gabriela ',
    title:            'Designer, UX/UI',
    biz:              'M|M Developers',
    slogan:           '2-Day Hand-Built Websites',
    mobile:           '+52 (55) ',
    bizPhone:         '',
    email:            '',
    bizEmail:         'gaby@magicmirror.dev',
    siteName:         '',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'http://g.page/mmdevs/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'https://linkedin.com/in/keck-james-keck',
    twitterLink:      'https://twitter.com/_techtranslator',
    fbLink:           'https://facebook.com/mmdevs',
    gitHub:           'https://facebook.com/mmdevs',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },


  {
    id :              11,
    name:             'Jose Palillero',
    title:            'Full-Stack Developer',
    biz:              'M|M Developers',
    slogan:           '2-Day Hand-Built Websites',
    mobile:           '',
    bizPhone:         '',
    email:            'jakkeck@gmail.com',
    bizEmail:         'jose@magicmirror.dev',
    siteName:         '',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'http://g.page/mmdevs/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'https://linkedin.com/in/keck-james-keck',
    twitterLink:      'https://twitter.com/_techtranslator',
    fbLink:           'https://facebook.com/mmdevs',
    gitHub:           'https://facebook.com/mmdevs',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              12,
    name:             'Erik Reyes',
    title:            'Plugger of Men',
    biz:              'Company Name',
    slogan:           'To plug butts is my mission',
    mobile:           '',
    bizPhone:         '',
    email:            'personal email',
    bizEmail:         'work email',
    siteName:         '',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'http://g.page/mmdevs/review?mt',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'https://linkedin.com/in/keck-james-keck',
    twitterLink:      'https://twitter.com/_techtranslator',
    fbLink:           'https://facebook.com/mmdevs',
    gitHub:           '',
    stkOvrflow:       '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

]
