import { Contact } from "./contact";

export const CONTACT: Contact[] = [
  {
    id : 0,
    name: 'Ryan Unkown',
    title: 'Chief Consultant',
    biz: 'AmWay',
    slogan: 'Building Financial Freedom',
    mobile: '(720) 512-1234',
    bizPhone: '(303) 593-0581',
    email: 'email@example.com',
    bizEmail: 'bizEmail@example.com',
    website: 'magicmirror.dev',
    calLink: 'ryanLink',
    fbLink: 'fbRyan',
    instaLink: 'instaRyan',
    linkedIn: 'linkProf',
    twitterLink: '',
    mainColor: '',
    secColor: '',
    accColor: ''
  },
  {
    id : 1,
    name: 'Wife Unkown',
    title: 'Chief Consultant',
    biz: 'Best Deal In Town',
    slogan: 'Be The Best Electronic Store',
    mobile: '(720) 512-1234',
    bizPhone: '(303) 593-0581',
    email: 'email@example.com',
    bizEmail: 'bizEmail@example.com',
    website: 'bestdealdenver.com',
    calLink: 'wifeLink',
    fbLink: 'fbWife',
    instaLink: 'instaWife',
    linkedIn: 'linkProf',
    twitterLink: '',
    mainColor: '',
    secColor: '',
    accColor: ''
  },
  {
    id : 2,
    name: 'Lisa Keck',
    title: 'Owner',
    biz: 'Plain & Fancy Caterers',
    slogan: 'For The Love of Food',
    mobile: '(336) 688-7787',
    bizPhone: '(336) 869-4842',
    email: 'jtkeck1@msn.com',
    bizEmail: '',
    website: 'plainandfancycaterers.com',
    calLink: '',
    fbLink: '',
    linkedIn: '',
    instaLink: '',
    twitterLink: '',
    mainColor: 'white',
    secColor: 'red',
    accColor: 'black'
  },
  {
    id : 3,
    name: 'Carla Pomicter',
    title: 'IT Compliance Analyst',
    biz: 'DHI Mortgage Company, Ltd.',
    slogan: 'Founded In Family, Built On Commitment',
    mobile: '(412) 952-4404',
    bizPhone: '(512) 257-5498',
    email: '',
    bizEmail: 'cpomicter@dhimortgage.com',
    website: 'dhimortgage.com',
    calLink: '',
    fbLink: '',
    instaLink: '',
    linkedIn: '',
    twitterLink: '',
    mainColor: '',
    secColor: '',
    accColor: ''
  },
  {
    id : 4,
    name: 'James Keck',
    title: 'Software Developer | CEO | Creator of Ideas',
    biz: 'M|M Developers',
    slogan: 'Hand-coded Websites in 2-Days',
    mobile: '(336) 880-0967',
    bizPhone: '(303) 593-0581',
    email: 'jakkeck@gmail.com',
    bizEmail: 'james@magicmirror.dev',
    website: 'magicmirror.dev',
    calLink: 'https://calendly.com/james-keck/connect',
    fbLink: '',
    instaLink: '',
    linkedIn: 'keck-james-keck',
    twitterLink: '_techtranslator',
    mainColor: '',
    secColor: '',
    accColor: ''
  }
]
