import { Contact } from "./contact";

export const CONTACT: Contact[] = [
  {
    id :              0,
    name:             'Ryan Unkown',
    title:            'Chief Consultant',
    biz:              'AmWay',
    slogan:           'Building Financial Freedom',
    mobile:           '(720) 512-1234',
    bizPhone:         '(303) 593-0581',
    email:            'email@example.com',
    bizEmail:         'bizEmail@example.com',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'ryanLink',
    fbLink:           'fbRyan',
    gglLink:          '',
    gglRev:           '',
    gglMap:           '',
    instaLink:        'instaRyan',
    linkedIn:         'linkProf',
    twitterLink:      '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },
  {
    id :              1,
    name:             'Wife Unkown',
    title:            'Chief Consultant',
    biz:              'Best Deal In Town',
    slogan:           'Be The Best Electronic Store',
    mobile:           '(720) 512-1234',
    bizPhone:         '(303) 593-0581',
    email:            'email@example.com',
    bizEmail:         'bizEmail@example.com',
    website:          'bestdealdenver.com',
    addr:             '',
    bizAddr:          '',
    calLink:          'wifeLink',
    fbLink:           'fbWife',
    gglLink:           '',
    gglRev:           '',
    gglMap:           '',
    instaLink:        'instaWife',
    linkedIn:         'linkProf',
    twitterLink:      '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },
  {
    id :              2,
    name:             'Lisa Keck',
    title:            'Owner',
    biz:              'Plain & Fancy Caterers',
    slogan:           'For The Love of Food',
    mobile:           '(336) 688-7787',
    bizPhone:         '(336) 869-4842',
    email:            'jtkeck1@msn.com',
    bizEmail:         '',
    website:          'plainandfancycaterers.com',
    addr:             '',
    bizAddr:          '',
    calLink:          '',
    fbLink:           '',
    gglLink:          '',
    gglRev:           '',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    mainColor:        'white',
    secColor:         'red',
    accColor:         'black'
  },
  {
    id :              3,
    name:             'Carla Pomicter',
    title:            'IT Compliance Analyst',
    biz:              'DHI Mortgage Company, Ltd.',
    slogan:           'Founded In Family, Built On Commitment',
    mobile:           '(412) 952-4404',
    bizPhone:         '(512) 257-5498',
    email:            '',
    bizEmail:         'cpomicter@dhimortgage.com',
    website:          'dhimortgage.com',
    addr:             '',
    bizAddr:          '',
    calLink:          '',
    fbLink:           '',
    gglLink:          '',
    gglRev:           '',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },
  {
    id :              4,
    name:             'James Keck',
    title:            'Software Developer | CEO | Creator of Ideas',
    biz:              'M|M Developers',
    slogan:           'Hand-coded Websites in 2-Days',
    mobile:           '(336) 880-0967',
    bizPhone:         '',
    email:            'jakkeck@gmail.com',
    bizEmail:         'james@magicmirror.dev',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    fbLink:           '',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'https://g.page/mmdevs/review?rc',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'keck-james-keck',
    twitterLink:      '_techtranslator',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              5,
    name:             'Andie Fernandez',
    title:            'Community Manager',
    biz:              'M|M Developers',
    slogan:           'Hand-coded Websites in 2-Days',
    mobile:           '+52 (55) 3434-3745',
    bizPhone:         '',
    email:            'cocosnar@gmail.com',
    bizEmail:         'andie@magicmirror.dev',
    website:          'magicmirror.dev',
    addr:             '',
    bizAddr:          '',
    calLink:          'https://calendly.com/james-keck/connect',
    fbLink:           '',
    gglLink:          'https://g.page/mmdevs?gm',
    gglRev:           'https://g.page/mmdevs/review?rc',
    gglMap:           '',
    instaLink:        '',
    linkedIn:         'keck-james-keck',
    twitterLink:      '_techtranslator',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              6,
    name:             'Cameron Montes',
    title:            'Operations Specialist',
    biz:              'Best Deal In Town',
    slogan:           'Discount Electronics',
    mobile:           '(720) 272-1279',
    bizPhone:         '(303) 593-0581',
    email:            '',
    bizEmail:         'cameronbestdealdenver@gmail.com',
    website:          'bestdealdenver.com',
    addr:             '4371 S Broadway \nEnglewood \nCO, 80113',
    bizAddr:          '',
    calLink:          '',
    fbLink:           'DenverHDTV',
    gglLink:          'https://g.page/bestDealDenver?gm',
    gglRev:           'http://g.page/bestDealDenver/review?mt',
    gglMap:          'https://www.google.com/maps?cid=3888086765111309119&_ga=2.102284673.1097732718.1598070129-22443877.1596228244',
    instaLink:        '',
    linkedIn:         '',
    twitterLink:      '',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },

  {
    id :              7,
    name:             'James Keck',
    title:            'Owner',
    biz:              'Best Deal In Town',
    slogan:           'Discount Electronics',
    mobile:           '(336) 880-0967',
    bizPhone:         '(303) 593-0581',
    email:            'jakkeck@gmail.com',
    bizEmail:         'best.deal.in.denver@gmail.com',
    website:          'bestdealdenver.com',
    addr:             '',
    bizAddr:          '4371 S Broadway \nEnglewood \nCO, 80113',
    calLink:          'https://calendly.com/james-keck/connect',
    fbLink:           'DenverHDTV',
    gglLink:          'https://g.page/bestDealDenver?gm',
    gglRev:           'http://g.page/bestDealDenver/review?mt',
    gglMap:          'https://www.google.com/maps?cid=3888086765111309119&_ga=2.102284673.1097732718.1598070129-22443877.1596228244',
    instaLink:        '',
    linkedIn:         'keck-james-keck',
    twitterLink:      '_techtranslator',
    mainColor:        '',
    secColor:         '',
    accColor:         ''
  },
]
